#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
        find ~/git ~/ -mindepth 1 -maxdepth 1 -type d -not -path '*/.*' |
        while read -r dir; do
            name=$(basename "$dir")
            if [[ "$name" == *-wk ]]; then
                continue  # worktrees are managed via 'wt', not here
            fi
            printf "\033[1m%s\033[0m\t%s\n" "$name" "$dir"
        done |
        fzf \
          --ansi \
          --delimiter=$'\t' \
          --with-nth=1 \
          --prompt='projects > ' \
          --border=rounded \
          --border-label=' tmux sessionizer ' \
          --header='enter: switch/create | esc: cancel' \
          --header-first \
          --info=inline-right \
          --preview='printf "\n %s\n" {2}' \
          --preview-window='down,3,border-top' \
          --preview-label=' path ' \
          --no-scrollbar \
          --cycle \
          --color='bg:-1,bg+:#313244,fg:#cdd6f4,fg+:#f5e0dc,hl:#f38ba8,hl+:#f38ba8,prompt:#cba6f7,pointer:#f5c2e7,marker:#a6e3a1,spinner:#f9e2af,info:#89b4fa,border:#45475a,label:#cba6f7,header:#7f849c' |
        cut -f2-
    )
fi


if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ "${TMUX-}" != '' ]]; then
    # Switch if inside of Tmux
    tmux switch-client -t $selected_name
else
    # Attach if outside of Tmux
    tmux attach -t "$selected_name"
fi
